# Stage 1 - build for production
# carbon is the latest LTS (Long Term Support) version of node available from Docker Hub
FROM node:carbon

# Create app directory
WORKDIR /usr/src/app

# COPY files: A wildcard is used to ensure both package.json AND package-lock.json are copied.
COPY package*.json yarn.lock ./

# Bundle app source code inside the Docker image
RUN yarn --frozen-lockfile
COPY . ./
RUN yarn build

# Stage 2 - set the production build ready for production with Nginx
#FROM nginx:alpine
#COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
#CMD ["nginx", "-g", "daemon off;"]
