
// Global configurations
export const CONFIG_SETTINGS = {
  defaultColumnSettings: {
    Samp_No: {alias: 'Sample Number', hide: false},
    SampleDate: {alias: 'Sample Date', hide: false},
    Matrix: {alias: 'Sample Type', hide: false},
    Analysis: {alias: 'Analysis', hide: false},
    AnalysisGroup: {alias: 'Analysis Group', hide: true},
    Analyte: {alias: 'Analyte', hide: false},
    Analyte_FinalName: {alias: 'Analyte Final Name', hide: true},
    Analytical_Method: {alias: 'Analytical Method', hide: true},
    Basis: {alias: 'Basis', hide: true},
    CAS_NO: {alias: 'CAS NO', hide: true},
    CLP_Sample_No: {alias: 'CLP Sample Number', hide: true},
    Comments: {alias: 'Comments', hide: true},
    Date_Analyzed: {alias: 'Date Analyzed', hide: true},
    Date_Collected: {alias: 'Date Collected', hide: true},
    Date_Edit: {alias: 'Date Edit', hide: true},
    Date_Extracted: {alias: 'Date Extracted', hide: true},
    Date_Input: {alias: 'Date Input', hide: true},
    Date_Received: {alias: 'Date Received', hide: true},
    Detected: {alias: 'Detected', hide: true},
    Dilution_Factor: {alias: 'Dilution Factor', hide: true},
    EDD_File_Name: {alias: 'EDD File Name', hide: true},
    Edited_By: {alias: 'Edited By', hide: true},
    Extraction_Method: {alias: 'Extraction Method', hide: true},
    Final_Volume: {alias: 'Final Volume', hide: true},
    Final_Volume_Unit: {alias: 'Final Volume Unit', hide: true},
    Lab_Batch_No: {alias: 'Lab Batch Number', hide: true},
    Lab_Coc_No: {alias: 'Lab Coc Number', hide: true},
    Lab_Location_ID: {alias: 'Lab Location ID', hide: true},
    Lab_Name: {alias: 'Lab Name', hide: true},
    Lab_Result_Qualifier: {alias: 'Lab Result Qualifier', hide: true},
    Lab_Samp_No: {alias: 'Lab Sample Number', hide: false},
    LabResultsID: {alias: 'Lab Results ID', hide: true},
    Matrix_ID: {alias: 'Matrix ID', hide: true},
    MDL: {alias: 'MDL', hide: false},
    MDL_Units: {alias: 'MDL Units', hide: true},
    Percent_Lipids: {alias: 'Percent Lipids', hide: true},
    Percent_Moisture: {alias: 'Percent Moisture', hide: true},
    Percent_Recovery: {alias: 'Percent Recovery', hide: true},
    Percent_Solids: {alias: 'Percent Solids', hide: true},
    QA_Comment: {alias: 'QA Comment', hide: true},
    QA_Date: {alias: 'QA Date', hide: true},
    QA_Username: {alias: 'QA Username', hide: true},
    QAFlag: {alias: 'QA Flad', hide: true},
    QC_Type: {alias: 'QC Type', hide: true},
    Quantitation_Limit: {alias: 'Quantitation Limit', hide: true},
    Quantitation_Limit_Units: {alias: 'Quantitation Limit Units', hide: true},
    Reportable_Result: {alias: 'Reportable Result', hide: false},
    Reporting_Limit: {alias: 'Reporting Limit', hide: false},
    Result: {alias: 'Result', hide: false},
    Result_Qualifier: {alias: 'Result Qualifier', hide: false},
    Result_Text: {alias: 'Result Text', hide: true},
    Result_Type_Code: {alias: 'Result Type Code', hide: true},
    Result_Units: {alias: 'Result Units', hide: false},
    Sample_No: {alias: 'Sample Number', hide: false},
    Sample_Type_Code: {alias: 'Sample Type Code', hide: true},
    Site_No: {alias: 'Site Number', hide: true},
    SubSample_Amount: {alias: 'Sub Sample Amount', hide: true},
    SubSample_Amount_Unit: {alias: 'Sub Sample Amount Unit', hide: true},
    Test_Type: {alias: 'Test Type', hide: true},
    Total_Or_Dissolved: {alias: 'Total or Dissolved', hide: true},
    Validation_Level: {alias: 'Validation Level', hide: true},
  },
  // query params and ag grid filter operand properties
  queryParamOperators: {
    equals: '',
    lessThan: '_lt',
    lessThanOrEqual: '_lte',
    greaterThan: '_gt',
    greaterThanOrEqual: '_gte',
  },
  agGridRelationalOperators: {
    _lt: 'lessThan',
    _lte: 'lessThanOrEqual',
    _gt: 'greaterThan',
    _gte: 'greaterThanOrEqual'
  },
  displayFilterOperators: {
    equals: '=',
    lessThan: '<',
    lessThanOrEqual: '<=',
    greaterThan: '>',
    greaterThanOrEqual: '>='
  },
  mapPointSymbolBreaks: 6,
  mapPointSymbolColors: {
    default: ['#fff7bc', '#fee391', '#ec7014', '#cc4c02', '#993404', '#662506'],
    water: ['#7fdfff', '#32cbff', '#4292c6', '#0077be', '#08519c', '#08306b'],
    air: ['#7fdfff', '#32cbff', '#4292c6', '#0077be', '#08519c', '#08306b'],
    soil: ['#fff7bc', '#fee391', '#ec7014', '#cc4c02', '#993404', '#662506'],
    solid: ['#fff7bc', '#fee391', '#ec7014', '#cc4c02', '#993404', '#662506']
  }
};
