
// Global configurations
export const CONFIG_SETTINGS = {
  defaultColumnSettings: {
    Samp_No: {alias: 'Sample Number', hide: false},
    SampleDate: {alias: 'Sample Date', hide: false},
    Matrix: {alias: 'Sample Type', hide: false},
    Analysis: {alias: 'Analysis', hide: false},
    AnalysisGroup: {alias: 'Analysis Group', hide: true},
    Analyte: {alias: 'Analyte', hide: false},
    Analyte_FinalName: {alias: 'Analyte Final Name', hide: true},
    Analytical_Method: {alias: 'Analytical Method', hide: true},
    Basis: {alias: 'Basis', hide: true},
    CAS_NO: {alias: 'CAS NO', hide: true},
    CLP_Sample_No: {alias: 'CLP Sample Number', hide: true},
    Comments: {alias: 'Comments', hide: true},
    Date_Analyzed: {alias: 'Date Analyzed', hide: true},
    Date_Collected: {alias: 'Date Collected', hide: true},
    Date_Edit: {alias: 'Date Edit', hide: true},
    Date_Extracted: {alias: 'Date Extracted', hide: true},
    Date_Input: {alias: 'Date Input', hide: true},
    Date_Received: {alias: 'Date Received', hide: true},
    Detected: {alias: 'Detected', hide: true},
    Dilution_Factor: {alias: 'Dilution Factor', hide: true},
    EDD_File_Name: {alias: 'EDD File Name', hide: true},
    Edited_By: {alias: 'Edited By', hide: true},
    Extraction_Method: {alias: 'Extraction Method', hide: true},
    Final_Volume: {alias: 'Final Volume', hide: true},
    Final_Volume_Unit: {alias: 'Final Volume Unit', hide: true},
    Lab_Batch_No: {alias: 'Lab Batch Number', hide: true},
    Lab_Coc_No: {alias: 'Lab Coc Number', hide: true},
    Lab_Location_ID: {alias: 'Lab Location ID', hide: true},
    Lab_Name: {alias: 'Lab Name', hide: true},
    Lab_Result_Qualifier: {alias: 'Lab Result Qualifier', hide: true},
    Lab_Samp_No: {alias: 'Lab Sample Number', hide: false},
    LabResultsID: {alias: 'Lab Results ID', hide: true},
    Matrix_ID: {alias: 'Matrix ID', hide: true},
    MDL: {alias: 'MDL', hide: false},
    MDL_Units: {alias: 'MDL Units', hide: true},
    Percent_Lipids: {alias: 'Percent Lipids', hide: true},
    Percent_Moisture: {alias: 'Percent Moisture', hide: true},
    Percent_Recovery: {alias: 'Percent Recovery', hide: true},
    Percent_Solids: {alias: 'Percent Solids', hide: true},
    QA_Comment: {alias: 'QA Comment', hide: true},
    QA_Date: {alias: 'QA Date', hide: true},
    QA_Username: {alias: 'QA Username', hide: true},
    QAFlag: {alias: 'QA Flad', hide: true},
    QC_Type: {alias: 'QC Type', hide: true},
    Quantitation_Limit: {alias: 'Quantitation Limit', hide: true},
    Quantitation_Limit_Units: {alias: 'Quantitation Limit Units', hide: true},
    Reportable_Result: {alias: 'Reportable Result', hide: false},
    Reporting_Limit: {alias: 'Reporting Limit', hide: false},
    Result: {alias: 'Result', hide: false},
    Result_Qualifier: {alias: 'Result Qualifier', hide: false},
    Result_Text: {alias: 'Result Text', hide: true},
    Result_Type_Code: {alias: 'Result Type Code', hide: true},
    Result_Units: {alias: 'Result Units', hide: false},
    Sample_No: {alias: 'Sample Number', hide: false},
    Sample_Type_Code: {alias: 'Sample Type Code', hide: true},
    Site_No: {alias: 'Site Number', hide: true},
    SubSample_Amount: {alias: 'Sub Sample Amount', hide: true},
    SubSample_Amount_Unit: {alias: 'Sub Sample Amount Unit', hide: true},
    Test_Type: {alias: 'Test Type', hide: true},
    Total_Or_Dissolved: {alias: 'Total or Dissolved', hide: true},
    Validation_Level: {alias: 'Validation Level', hide: true},

    // Sample Point Locations fields
    SamplesID: {alias: 'Sample ID', hide: false},
    Site_Number: {alias: 'Site Number', hide: true},
    EventID: {alias: 'Event ID', hide: true},
    Sample_Number: {alias: 'Sample Number', hide: false},
    Sample_Date: {alias: 'Sample Date', hide: false},
    SampleTime: {alias: 'Sample Time', hide: false},
    Location: {alias: 'Location', hide: false},
    Sub_Location: {alias: 'Sub Location', hide: true},
    // Matrix: {alias: 'Sample Type', hide: false},
    SampleMedia: {alias: 'Sample Media', hide: true},
    SampleCollection: {alias: 'Sample Collection', hide: true},
    SampleType: {alias: 'Sample Collection Type', hide: true},
    Activity: {alias: 'Activity', hide: true},
    Samp_Depth: {alias: 'Sample Depth', hide: false},
    Samp_Depth_To: {alias: 'Sample Depth To', hide: false},
    Samp_Depth_Units: {alias: 'Sample Depth Units', hide: false},
    Volume: {alias: 'Volume', hide: true},
    Volume_Units: {alias: 'Volume Units', hide: true},
    Samp_Concentration: {alias: 'Sample Concentration', hide: true},
    Sampler: {alias: 'Sampler', hide: true},
    Witness: {alias: 'Witness', hide: true},
    LinkSampleNo: {alias: 'Link Sample Number', hide: true},
    Image_Path: {alias: 'Image Path', hide: true},
    Remarks: {alias: 'Remarks', hide: true},
    LabResultsAvailable: {alias: 'Lab Results Available', hide: true},
    Task_ID: {alias: 'Task ID', hide: true},
    // Date_Input: {alias: 'Date Input', hide: true},
    // Date_Edit: {alias: 'Date_Edit', hide: true},
    // Edited_By: {alias: 'Edited_By', hide: true},
    SiteID: {alias: 'Site ID', hide: true},
    Site_Numb: {alias: 'Site Number', hide: true},
    Option_Period: {alias: 'Option Period', hide: true},
    Site_Name: {alias: 'Site Name', hide: false},
    Area: {alias: 'Area', hide: false},
    Site_State: {alias: 'Site State', hide: true},
    Site_Phone: {alias: 'Site Phone', hide: true},
    Description: {alias: 'Description', hide: true},
    Site_Action: {alias: 'Site Action', hide: true},
    DO_Number: {alias: 'DO Number', hide: true},
    CERCLIS: {alias: 'CERCLIS', hide: true},
    AccountCode: {alias: 'Account Code', hide: true},
    ProjectCode: {alias: 'Project Code', hide: true},
    Numeric_Tags: {alias: 'Numeric Tags', hide: true},
    CaseNumber: {alias: 'Case Number', hide: true},
    Next_CLP_Sample_No: {alias: 'Next CLP Sample No', hide: true},
    Next_Tag: {alias: 'Next Tag', hide: true},
    Region_Tag_Prefix: {alias: 'Region Tag Prefix', hide: true},
    Response_Authority: {alias: 'Response Authority', hide: true},
    NPL_Status: {alias: 'NPL Status', hide: true},
    DASNumber: {alias: 'DAS Number', hide: true},
    EPARegionNumber: {alias: 'EPA Region Number', hide: true},
    EPA_OrgName: {alias: 'EPA Org Name', hide: true},
    EPAContract_No: {alias: 'EPA Contract No', hide: true},
    EPAProj_No: {alias: 'EPA Project No', hide: true},
    EPAContact: {alias: 'EPA Contact', hide: true},
    EPAPhone: {alias: 'EPA Phone', hide: true},
    Contract_Name: {alias: 'Contract Name', hide: true},
    Contractor: {alias: 'Contractor', hide: false},
    CTRContact: {alias: 'CTR Contact', hide: false},
    Address1: {alias: 'Address1', hide: true},
    Address2: {alias: 'Address2', hide: true},
    City: {alias: 'City', hide: true},
    State: {alias: 'State', hide: true},
    Zip: {alias: 'Zip', hide: true},
    CTRPhone: {alias: 'CTR Phone', hide: true},
    CTRWano: {alias: 'CTR Wano', hide: true},
    Unit_Of_Meas: {alias: 'Unit Of Measure', hide: true},
    Control_No: {alias: 'Control Number', hide: true},
    VER_NO: {alias: 'Version Number', hide: true},
    Template_File_Path: {alias: 'Template File Path', hide: true},
    ScribeNetProjectID: {alias: 'Scribe Net Project ID', hide: true},
    ScribeNetCustomerID: {alias: 'Scribe Net Customer ID', hide: true},
    CLP_Tag_Mask: {alias: 'CLP Tag Mask', hide: true},
    Project_Default: {alias: 'Project Default', hide: true},
    LocationID: {alias: 'Location ID', hide: true},
    PropertyID: {alias: 'Property ID', hide: true},
    LocationDescription: {alias: 'Location Description', hide: true},
    LocationZone: {alias: 'Location Zone', hide: true},
    Latitude: {alias: 'Latitude', hide: false},
    Longitude: {alias: 'Longitude', hide: false},
    Altitude: {alias: 'Altitude', hide: true},
    GPS_PDOP: {alias: 'GPS PDOP', hide: true},
    GPS_CorrectionType: {alias: 'GPS Correction Type', hide: true},
    GPS_Date: {alias: 'GPS Date', hide: true},
    GPS_Time: {alias: 'GPS Time', hide: true},
    GPS_Collected_By: {alias: 'GPS Collected By', hide: true},
    GPS_Comment: {alias: 'GPS Comment', hide: true},
    GPS_Phase: {alias: 'GPS Phase', hide: true},
    Northing: {alias: 'Northing', hide: true},
    Easting: {alias: 'Easting', hide: true},
    Datum: {alias: 'Datum', hide: true},
    GeoMethod: {alias: 'Geo Method', hide: true},
    GeoScale: {alias: 'Geo Scale', hide: true},
    Surf_Elev: {alias: 'Surf Elevation', hide: true},
    Surf_Units: {alias: 'Surf Units', hide: true},
    ElevMethod: {alias: 'Elevation Method', hide: true},
    ElevDatum: {alias: 'Elevation Datum', hide: true},
    Coord_Sys_Desc: {alias: 'Coord System Desc.', hide: true},
    LocationComment: {alias: 'Location Comment', hide: true},
    Location_Image_Path: {alias: 'Location Image Path', hide: true}
  },
  // query params and ag grid filter operand properties
  queryParamOperators: {
    equals: '',
    lessThan: '_lt',
    lessThanOrEqual: '_lte',
    greaterThan: '_gt',
    greaterThanOrEqual: '_gte',
  },
  agGridRelationalOperators: {
    _lt: 'lessThan',
    _lte: 'lessThanOrEqual',
    _gt: 'greaterThan',
    _gte: 'greaterThanOrEqual'
  },
  displayFilterOperators: {
    equals: '=',
    lessThan: '<',
    lessThanOrEqual: '<=',
    greaterThan: '>',
    greaterThanOrEqual: '>='
  },
  mapPointSymbolBreaks: 6,
  mapPointSymbolColors: {
    default: ['#fff7bc', '#fee391', '#ec7014', '#cc4c02', '#993404', '#662506'],
    water: ['#7fdfff', '#32cbff', '#4292c6', '#0077be', '#08519c', '#08306b'],
    air: ['#7fdfff', '#32cbff', '#4292c6', '#0077be', '#08519c', '#08306b'],
    soil: ['#fff7bc', '#fee391', '#ec7014', '#cc4c02', '#993404', '#662506'],
    solid: ['#fff7bc', '#fee391', '#ec7014', '#cc4c02', '#993404', '#662506']
  }
};
