version: '3.6'

x-common-variables: &common-variables
  NODE_ENV: ${NODE_ENV}
  DEBUG: ${DEBUG}
  ALLOWED_HOST: ${ALLOWED_HOST}
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DJANGO_PORT: ${DJANGO_PORT}
  CORS_ORIGIN_WHITELIST: ${CORS_ORIGIN_WHITELIST}
  STATIC_URL: ${STATIC_URL}


services:
  db:
    image: domain.com/template-postgres:latest
    build:
      context: ./backend
      dockerfile: Dockerfile_db
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: on-failure
  backend:
    image: domain.com/template-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
      args:
        <<: *common-variables
    environment:
      <<: *common-variables
    depends_on:
      - db
    command: /code/django_entrypoint.sh
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    restart: on-failure
  frontend:
    image: domain.com/template-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile_frontend
    environment:
      NODE_ENV: ${NODE_ENV}
      <<: *common-variables
  pgadmin4:
      image: dpage/pgadmin4:latest
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - "10052:80"
      restart: on-failure
      depends_on:
        - db

