FROM python:3
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
COPY django_entrypoint.sh /code/

RUN pip install pip --upgrade
RUN pip install -r requirements.txt

COPY . /code/

