
# models generated by build_data_models management command:
# python manage.py build_data_models --database=scribe_db --owner=sa --path=models_path
from .dbo import *

# models generated by inspectdb command:
# python manage.py inspectdb --database=scribe_db Table Name (e.g. Projects) > scribe_models/models/scribe_models.py
from .scribe_models import Projects
