
# models generated by build_data_models management command:
# python manage.py build_data_models --database=scribe_db --owner=sa --path=models_path
from .dbo import *

from .scribe_base_models import Projects
