
# models generated by build_data_models management command:
# python manage.py build_data_models --database=scribe_db --owner=sa --path=models_path
from backend.scribe_models.models.dbo import *

from backend.scribe_models.models.scribe_base_models import Projects
